### ISSUE TITLE
Services API allows other to expose custom API's or modify/hook into entities, and add actions/targetable actions or indexes.

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/services#2]
Research and propose implementation

**Comment by nerdstein** [comment]
@kylebrowning - questions to resolve:
1. What are some examples of this?
2. What fields/attributes/features do you need Services to provide? (generally speaking, not prescribing the solution)
3. What are known gaps with D8's services now?

**Comment by nerdstein** [comment]
Possible options:
1. Plugin manager / interface for allowing other modules to implement their APIs
2. A `Services` service/controller which standardizes an interface and pulls in these plugin instances within submodules

**Comment by kylebrowning** [comment]
@nerdstein 
1. Some examples include, https://www.drupal.org/node/750036. The idea is that some modules may want to expose data that isn't really an entity, how do they do that? Services d5-6-7  allowed any contributed module to do this
2. Im not sure i understand the questions
3. Known gaps are really just that its not an API for API's its just a REST API that only allows you to CRUD entities. For example, how do you password reset via an HTTP call?

**Comment by kylebrowning** [comment]
Another gap, which is in another ticket is, #3

**Comment by kylebrowning** [comment]
![Services add endpoint screen](https://www.evernote.com/l/ADi6WsjerilD-Z-RxmTXzuCfvvcSaHnrZ0MB/image.png)

**Comment by nerdstein** [comment]
@kylebrowning - is this ticket the D7 equivalent?

**Comment by nerdstein** [comment]
We have a couple things going on here... We have "service instances" which are instances of "Service definitions", exposed by modules. 

Service definitions define expected operations (actions/targeted actions) and their callbacks. They define the expected arguments. Modules maintain the callbacks to execute the action. The module should be expected to define a validation routine on top of the callback. Actions are on entities and/or bundles, targeted actions are on instances - the logic is defined in the respective module.

Service instances are created by selecting a service definition, creating an endpoint, and _somehow_ defining the arguments either as part of the endpoint or part of the request (e.g. a table of the expected arguments and their source from the request). Other features like authentication need to be considered here.

The services module basically exposes a deriver between a routing request and the defined service instance endpoints. It should invoke the validation routine and then the execution. It also provides the interface for creating service instances (best done as a ctools wizard), and exposes the service definition plugin manager for modules to define their own types of service instances.

@kylebrowning - confirm please

**Comment by kylebrowning** [comment]
> We have a couple things going on here... We have "service instances" which are instances of "Service definitions", exposed by modules.

Correct

> Service definitions define expected operations (actions/targeted actions) and their callbacks. They define the expected arguments. Modules maintain the callbacks to execute the action. The module should be expected to define a validation routine on top of the callback. Actions are on entities and/or bundles, targeted actions are on instances - the logic is defined in the respective module.

Service definitions and the term Resources are mutually exclusive.

> Service instances are created by selecting a service definition, creating an endpoint, and somehow defining the arguments either as part of the endpoint or part of the request (e.g. a table of the expected arguments and their source from the request). Other features like authentication need to be considered here.

You may be getting confused here, the Service definitions define the arguments, Services will validate on those arguments in a default manner like, is this argument required, does it exist, etc...

> The services module basically exposes a deriver between a routing request and the defined service instance endpoints. It should invoke the validation routine and then the execution. It also provides the interface for creating service instances (best done as a ctools wizard)
> That is correct up to this point,
> , and exposes the service definition plugin manager for modules to define their own types of service instances.

Should read, , and exposes the service definition plugin manager for modules to define their own types of ~~service instances~~ resources.

Now if you're saying you want people to be able to define their own service instances in code instead of the manager, then yes that sentence is still valid.

**Comment by nerdstein** [comment]
We're on the same page. Service Instances should be config entities, so they can be exported as code.

All of your other comments, I believe, make sense.

Why not use the term "Service Definition" - resource is ambiguous.

**Comment by kylebrowning** [comment]
no reason not to.

**Comment by kylebrowning** [comment]
Except that Services in d5 d6 and d7 used resources.

**Comment by nerdstein** [comment]
Closing, new tickets coming
