### ISSUE TITLE
Provide endpoint capabilities to put your API behind a centralized URL

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/services#3]
Research and implement

**Comment by nerdstein** [comment]
This can use a dynamic routing plugin that interfaces with the Plugin Manager of issue #1 

Example as seen in:
`core/modules/field_ui/src/Routing/RouteSubscriber.php`
and
`core/modules/field_ui/field_ui.services.yml`

**Comment by kylebrowning** [comment]
This needs to be an interface that allows you to define an endpoint, like '/api', or '/mobile-api'

Endpoints need configuration options like, Different authentication mechanisms per endpoint. Theres a screenshot in #2

**Comment by nerdstein** [comment]
OK, we would probably want to make authentication pluggable as well

**Comment by nerdstein** [comment]
See comment in issue #2

**Comment by nerdstein** [comment]
Closing, new tickets coming
