### ISSUE TITLE
Provide abstraction from some of cores annoyances. Like hal_json POST only instead of just JSON acceptance.

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/services#5]
Research and implement

**Comment by nerdstein** [comment]
This needs some substantial elaboration.

From reading, core is forcing one format (maybe this is a plugin system that could be extended). So the general idea is that services extends support for more formats. Correct?

This almost seems better suited for a core patch, but services may be a good pilot for staging potential core features

**Comment by nerdstein** [comment]
So my gut tells me that we should triple check and make sure core doesn't have a pluggable system for these formats.

If it does, services can provide some and leverage them as well. If it doesn't, well, we make a pluggable system for it's endpoints

**Comment by kylebrowning** [comment]
Im guess it does, but that only means we need to include them, my gut tells me we will still have to write our own. For Example, to get XML, and to get Regular JSON.

**Comment by nerdstein** [comment]
Closing, new tickets coming
