### ISSUE TITLE
Create request processing system for Service Instances

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/services#9]
1. Retrieve the endpoint from each service instance, register dynamically in dynamic router to ServiceRequest controller
2. Return the ServiceRequest controller function that processes the request by associating the endpoint back to the ServiceInstance and it's associated ServiceProvider

**Comment by nerdstein** [comment]
Known gaps / considerations:

Routing/ServiceAPI.php has '_access'=>'TRUE'

We need to look at the various core provided Drupal\Core\Routing\Access\AccessInterface and consider building an "access control" area into the ServiceAPI entity. This _could be_ complimentary and/or replace the _authentication_ requirement

**Comment by nerdstein** [comment]
Again - remaining requirements here are around the authentication / access control of a Service API endpoint.

Please add a field to the Service API entity and form to select an optional Drupal\Core\Routing\Access\AccessInterface. There may need to be additional options or fields needed based on the selected AccessInterface, but please report back with findings after initial research.

To enforce this authentication, evaluate any/all of the following components:
1. Routing/ServiceAPI.php
2. The EventSubscriber defined in issue #12 
3. The Services Controller
3. The ServiceManager service

**Comment by kylebrowning** [comment]
Hold off on this for the time being, we are having some discussions around this.

**Comment by kylebrowning** [comment]
@nerdstein I think this can be deleted?
